### ISSUE TITLE
latlon grid can be pre-made

### ISSUE THREAD

**Issue by ifenty** [ECCO-GROUP/ECCO-ACCESS#76]
https://github.com/ECCO-GROUP/ECCO-ACCESS/blob/c5c1b3dca3002cad61b1792f6a4de9017a25a891/generating_netcdf/V1_cloud/lambda_code/eccov4r4_gen_for_podaac_cloud.py#L173

just like the mapping factors

**Comment by DuncanBark** [comment]
latlon grid now pre-made, saved, and loaded when needed. This also creates the mapping factors and land mask in the master_script
