### ISSUE TITLE
wrap long lines

### ISSUE THREAD

**Issue by ifenty** [ECCO-GROUP/ECCO-ACCESS#78]
https://github.com/ECCO-GROUP/ECCO-ACCESS/blob/c5c1b3dca3002cad61b1792f6a4de9017a25a891/generating_netcdf/V1_cloud/lambda_code/eccov4r4_gen_for_podaac_cloud.py#L400

**Comment by DuncanBark** [comment]
Fixed long lines where possible/makes sense
