### ISSUE TITLE
record time dictionary near where record times are defined ( a few lines up)

### ISSUE THREAD

**Issue by ifenty** [ECCO-GROUP/ECCO-ACCESS#79]
https://github.com/ECCO-GROUP/ECCO-ACCESS/blob/c5c1b3dca3002cad61b1792f6a4de9017a25a891/generating_netcdf/V1_cloud/lambda_code/eccov4r4_gen_for_podaac_cloud.py#L399

**Comment by DuncanBark** [comment]
Done, changed references to "record_times" to match (previously were "record_time") in "global_DS_changes()"
