### ISSUE TITLE
look for file paths using exact match (after splitting on /), instead of 'in'

### ISSUE THREAD

**Issue by ifenty** [ECCO-GROUP/ECCO-ACCESS#81]
https://github.com/ECCO-GROUP/ECCO-ACCESS/blob/c5c1b3dca3002cad61b1792f6a4de9017a25a891/generating_netcdf/V1_cloud/lambda_code/eccov4r4_gen_for_podaac_cloud.py#L286

**Comment by ifenty** [comment]
but still make sure there is only one!

**Comment by DuncanBark** [comment]
done
