### ISSUE TITLE
A smaller argument of for 'generate_netcdfs' could be possible

### ISSUE THREAD

**Issue by ifenty** [ECCO-GROUP/ECCO-ACCESS#84]
https://github.com/ECCO-GROUP/ECCO-ACCESS/blob/c5c1b3dca3002cad61b1792f6a4de9017a25a891/generating_netcdf/V1_cloud/lambda_code/master_script.py#L184

From SASSIE.  most directories are now coded in the product_generation_config.json file in 'metadata_dir'.

'array precision' should  be in product_generation and not hard coded (what was I thinking?)

'time_step_selection_method' is nothing to replicate.

```
G, ecco_grid =  generate_netcdfs(output_freq_code, job_id, num_jobs,
                             product_type,
                             metadata_dir,
                             array_precision,
                             grouping_to_process,
                             time_step_selection_method,
                             debug_mode)

```

**Comment by DuncanBark** [comment]
New call uses "config_metadata" dictionary (from "product_generation_config.json"), which now makes it much shorter than before
